#!/usr/bin/env bash
# check_special_form_enum.sh — the analyzer's special-form set is a RECORDED
# decision, never an accident.
#
#   bash scripts/check_special_form_enum.sh          # gate: assert the set matches
#   bash scripts/check_special_form_enum.sh --write  # regenerate the ledger
#
# ADR-0004 locked the special-form enum's shape on day one and requires an
# amendment to add a slot. Nothing enforced that: as of 2026-08-20 the ADR
# reserved 10 variants the enum never gained (`the`, `catch`, `finally`,
# `deftype`, `defrecord`, `reify`, `definterface`, `monitor_enter`,
# `monitor_exit`, `dosync`) while the enum had gained 7 the ADR never mentioned
# (`defmacro_form`, `letfn_star`, `binding_form`, `in_ns_form`, `require_form`,
# `ns_form`, `mut_fields`) — the reservation and the code had not agreed for a
# long time, and no run of anything said so.
#
# This gate does NOT parse the ADR's prose (it names slots in a sentence, with
# different spellings than the code: `if` vs `if_form`). It pins the CODE's set
# in a ledger instead, so a variant cannot appear or vanish silently — and the
# moment you update the ledger is the moment to amend ADR-0004. Same shape as
# `data/doc_coverage.txt`: a ledger of decisions, not a target.
set -euo pipefail
cd "$(dirname "$0")/.."

SOURCE="src/eval/analyzer/analyzer.zig"
LEDGER="data/special_forms.txt"

[ -f "$SOURCE" ] || { echo "check_special_form_enum: $SOURCE is missing" >&2; exit 1; }

# The variant names inside `const SpecialFormKind = enum { … };`. Bare
# identifiers followed by a comma, so a comment line or a nested brace cannot
# masquerade as a variant.
actual="$(awk '
  /^const SpecialFormKind = enum \{/ { in_enum = 1; next }
  in_enum && /^\};/                  { exit }
  in_enum                            { print }
' "$SOURCE" | sed -n 's/^[[:space:]]*\([a-z_][a-z0-9_]*\),[[:space:]]*$/\1/p' | LC_ALL=C sort)"

[ -n "$actual" ] || { echo "check_special_form_enum: parsed ZERO variants from $SOURCE — the enum's shape changed and this parser did not" >&2; exit 1; }

if [[ "${1:-}" == "--write" ]]; then
    {
        echo "# GENERATED by scripts/check_special_form_enum.sh --write — the exact set"
        echo "# of \`SpecialFormKind\` variants in $SOURCE."
        echo "#"
        echo "# ADR-0004 locks this enum's shape; adding or removing a name here is an"
        echo "# amendment to that ADR, not a formality. The gate asserts the code still"
        echo "# matches this file, so neither side can drift without the other."
        printf '%s\n' "$actual"
    } > "$LEDGER"
    echo "check_special_form_enum: wrote $(printf '%s\n' "$actual" | grep -c .) variants to $LEDGER"
    exit 0
fi

[ -f "$LEDGER" ] || { echo "check_special_form_enum: $LEDGER is missing — run with --write" >&2; exit 1; }

expected="$(grep -v '^#' "$LEDGER" | grep . | LC_ALL=C sort)"

if [[ "$actual" == "$expected" ]]; then
    echo "check_special_form_enum: ok — $(printf '%s\n' "$actual" | grep -c .) special forms, ledger matches the enum"
    exit 0
fi

echo "check_special_form_enum: VIOLATION -- the analyzer's special-form set no longer matches $LEDGER." >&2
added="$(comm -23 <(printf '%s\n' "$actual") <(printf '%s\n' "$expected"))"
removed="$(comm -13 <(printf '%s\n' "$actual") <(printf '%s\n' "$expected"))"
[ -n "$added" ]   && { echo "  ADDED in code, absent from the ledger:" >&2;   printf '%s\n' "$added"   | sed 's/^/    + /' >&2; }
[ -n "$removed" ] && { echo "  IN the ledger, absent from code:" >&2;         printf '%s\n' "$removed" | sed 's/^/    - /' >&2; }
echo "  ADR-0004 locks this enum. Amend it (Revision history), then run --write." >&2
exit 1
