#!/usr/bin/env bash
# check_adr_affected_files.sh — ADR-0020 mandates an "Affected files" section.
# This enforces it for NEW ADRs and pins the grandfathered backlog.
#
#   bash scripts/check_adr_affected_files.sh          # gate
#   bash scripts/check_adr_affected_files.sh --write  # regenerate the ledger
#
# ADR-0020 required the section from its own number onward and nothing checked
# it, so 51 of the 172 ADRs numbered >= 0020 never got one. Retrofitting those
# by hand would mean reconstructing each decision's file list from memory years
# later — writing a record rather than keeping one — so they are GRANDFATHERED
# by name in `data/adr_affected_files_grandfathered.txt`, and the mandate binds
# for every ADR above the high-water mark recorded there.
#
# The ledger is checked in BOTH directions, like data/doc_coverage.txt:
#   - an ADR above the mark with no section FAILS (the mandate);
#   - an ADR at or below the mark that is NOT listed FAILS (someone deleted a
#     section, or renumbered a file);
#   - a LISTED ADR that has since GAINED a section FAILS, asking you to drop it
#     from the ledger — so the backlog can only shrink, never silently regrow.
set -euo pipefail
cd "$(dirname "$0")/.."

LEDGER="data/adr_affected_files_grandfathered.txt"
gate=1
[ "${1:-}" = "--write" ] && gate=0

# ADR-0000 predates the mandate; ADR-0020 is where it starts.
adrs_from_20() {
  for f in .dev/decisions/[0-9][0-9][0-9][0-9]_*.md; do
    [ -e "$f" ] || continue
    n="$(basename "$f" | grep -oE '^[0-9]{4}')"
    [ "$((10#$n))" -ge 20 ] || continue
    printf '%s\n' "$f"
  done
}

has_section() { grep -q '^## Affected files' "$1"; }

missing_now="$(adrs_from_20 | while IFS= read -r f; do has_section "$f" || basename "$f"; done | LC_ALL=C sort)"

if [ "$gate" -eq 0 ]; then
    mark="$(adrs_from_20 | tail -1 | xargs basename | grep -oE '^[0-9]{4}')"
    {
        echo "# GENERATED by scripts/check_adr_affected_files.sh --write"
        echo "#"
        echo "# ADRs that predate enforcement of ADR-0020's \"Affected files\" mandate and"
        echo "# are grandfathered. The mandate BINDS for every ADR numbered above the"
        echo "# high-water mark below; these are exempt because reconstructing their file"
        echo "# lists now would fabricate a record rather than keep one."
        echo "#"
        echo "# This list may only SHRINK. Adding a section to one of these is welcome —"
        echo "# drop its line here in the same commit."
        echo "high-water-mark: $mark"
        printf '%s\n' "$missing_now"
    } > "$LEDGER"
    echo "check_adr_affected_files: wrote $(printf '%s\n' "$missing_now" | grep -c .) grandfathered ADRs (mark $mark) to $LEDGER"
    exit 0
fi

[ -f "$LEDGER" ] || { echo "check_adr_affected_files: $LEDGER missing — run with --write" >&2; exit 1; }

mark="$(grep '^high-water-mark:' "$LEDGER" | awk '{print $2}')"
[ -n "$mark" ] || { echo "check_adr_affected_files: $LEDGER has no high-water-mark line" >&2; exit 1; }
grandfathered="$(grep -v '^#' "$LEDGER" | grep -v '^high-water-mark:' | grep . | LC_ALL=C sort)"

fail=0

# 1. Any ADR ABOVE the mark must carry the section — no exemptions.
while IFS= read -r f; do
    [ -z "$f" ] && continue
    n="$(basename "$f" | grep -oE '^[0-9]{4}')"
    [ "$((10#$n))" -gt "$((10#$mark))" ] || continue
    if ! has_section "$f"; then
        echo "check_adr_affected_files: VIOLATION -- $f is above the grandfather mark ($mark) and has no '## Affected files' section (ADR-0020)." >&2
        fail=1
    fi
done < <(adrs_from_20)

# 2. A grandfathered ADR that GAINED the section should leave the ledger.
while IFS= read -r b; do
    [ -z "$b" ] && continue
    f=".dev/decisions/$b"
    if [ ! -f "$f" ]; then
        echo "check_adr_affected_files: VIOLATION -- $LEDGER lists $b, which no longer exists." >&2
        fail=1
    elif has_section "$f"; then
        echo "check_adr_affected_files: VIOLATION -- $b now HAS an '## Affected files' section; drop it from $LEDGER." >&2
        fail=1
    fi
done <<< "$grandfathered"

# 3. An ADR at/below the mark missing the section must be listed (a deleted
#    section, or a renumbered file, would otherwise pass unnoticed).
unlisted="$(comm -23 <(printf '%s\n' "$missing_now") <(printf '%s\n' "$grandfathered"))"
if [ -n "$unlisted" ]; then
    echo "check_adr_affected_files: VIOLATION -- missing the section and NOT grandfathered:" >&2
    printf '%s\n' "$unlisted" | sed 's/^/    /' >&2
    fail=1
fi

[ "$fail" -eq 0 ] || exit 1
echo "check_adr_affected_files: ok — mandate enforced above ADR-$mark, $(printf '%s\n' "$grandfathered" | grep -c .) grandfathered"
