#!/usr/bin/env bash
# gen_placement.sh — regenerate data/placement.yaml from code truth (ADR-0178).
#
#   bash scripts/gen_placement.sh            # rewrite data/placement.yaml
#   bash scripts/gen_placement.sh --stdout   # print, do not write
#
# Where a var's implementation lives is a property of the code, and the runtime
# already knows it: a Var's root is a `builtin_fn` when a Zig primitive interned
# it, and a `fn_val` when a `(def …)` in a bundled `.clj` produced it. So the
# placement index is DERIVED, not maintained.
#
# History (ADR-0178): the hand-written predecessor covered 49 of ~683
# `clojure.core` publics, cited three helper scripts of which two never existed,
# was wired into no gate, and had drifted far enough to contradict the code — 42
# rows still read `transient_zig` for vars whose `.clj` migration D-062 recorded
# as discharged on 2026-05-27. A hand-fed index of a mechanical fact rots; this
# is the same fix `check_compat_members.sh` applied to compat_tiers member lists
# (ADR-0174 D9).
#
# Every bundled namespace is `require`d first — namespaces load lazily
# (ADR-0163), so a bare dump would only see the eager set and silently under-report.
set -euo pipefail
cd "$(dirname "$0")/.."

BIN="zig-out/bin/cljw"
[ -n "${CLJW_SKIP_BUILD:-}" ] || zig build -Dwasm -Doptimize="${CLJW_OPT:-ReleaseSafe}" >/dev/null
# Bundled .clj → ns name (same munge inverse as check_lazy_ns_replay.sh:
# '/'→'.', '_'→'-').
mapfile -t NSES < <(
    find src/lang/clj -name '*.clj' \
      | sed 's|^src/lang/clj/||; s|\.clj$||' \
      | tr '/' '.' | tr '_' '-' \
      | sort
)

REQUIRES=""
for ns in "${NSES[@]}"; do
    REQUIRES="$REQUIRES(try (require '$ns) (catch Throwable _ nil))"
done

RAW="$("$BIN" -e "${REQUIRES}(print (cljw.internal/__dump-placement))" 2>/dev/null)"
[ -n "$RAW" ] || { echo "gen_placement: empty dump — is __dump-placement wired?" >&2; exit 1; }

emit() {
    printf '%s\n' "$RAW" | awk -v nscount="${#NSES[@]}" '
    /^V / {
        split($2, parts, "/")
        # A var name may itself contain "/" (e.g. clojure.core//). Rejoin all
        # but the first segment.
        ns = parts[1]
        name = substr($2, length(ns) + 2)
        impl = $3
        flags = $4
        key = $2
        rows[++n] = key "\t" impl "\t" flags
        count[impl]++
        next
    }
    END {
        print "# GENERATED by scripts/gen_placement.sh — do not hand-edit."
        print "#"
        print "# Where every interned Var'\''s implementation lives, derived from the running"
        print "# runtime via (cljw.internal/__dump-placement) after requiring every bundled"
        print "# namespace. The `placement_drift` gate in test/run_all.sh regenerates this"
        print "# file and fails on any difference, so it cannot disagree with the code."
        print "#"
        print "# impl:"
        print "#   zig     — root is a builtin_fn: a Zig primitive interned from"
        print "#             lang/primitive/** (ADR-0033 Pattern B1, or a B2 `-name` leaf —"
        print "#             the zig-leaf flag separates those two)."
        print "#   clj     — root is a fn_val / multi_fn: produced by a (def …) in a bundled"
        print "#             .clj (Pattern A composition, a B2 one-line shim, or C-thin)."
        print "#   value   — not a function (a var holding data, e.g. *out*)."
        print "#   unbound — declared with no root ((def x) / internDeclare)."
        print "#"
        print "# What this file does NOT record: whether the current placement is the"
        print "# INTENDED final one. That is a judgement, not a fact, so it lives in"
        print "# .dev/debt.yaml where it can carry a barrier — today exactly one var"
        print "# (clojure.string/escape, D-094). ADR-0033 D2-D5 remains the placement rule."
        print "#"
        print "# Read with yq per .claude/rules/yaml_ssot_yq.md."
        print ""
        print "schema_version: \"2.0\""
        print "summary:"
        printf "  namespaces_required: %d\n", nscount
        printf "  total: %d\n", n
        printf "  zig: %d\n", count["zig"] + 0
        printf "  clj: %d\n", count["clj"] + 0
        printf "  value: %d\n", count["value"] + 0
        printf "  unbound: %d\n", count["unbound"] + 0
        print "vars:"
        # Sorted so the drift diff is stable across map-iteration order — and
        # LC_ALL=C so it is stable across HOSTS too. Without it, macOS and GNU
        # sort disagree on where punctuation and case fall (`*`, `!`, `-`), so
        # the identical var set produced a different file on each host and the
        # drift gate failed on the x86_64 leg with a pure reordering diff.
        for (i = 1; i <= n; i++) print rows[i] | "LC_ALL=C sort"
        close("LC_ALL=C sort")
    }' | awk -F'\t' '
        /^[^ #]/ && NF == 3 {
            gsub(/"/, "\\\"", $1)
            printf "  \"%s\": { impl: %s, flags: \"%s\" }\n", $1, $2, $3
            next
        }
        { print }
    '
}

if [[ "${1:-}" == "--stdout" ]]; then
    emit
else
    emit > data/placement.yaml
    echo "gen_placement: wrote data/placement.yaml ($(grep -c '^  "' data/placement.yaml) vars from ${#NSES[@]} namespaces)"
fi
