(require '[clojure.java.io :as io] '[clojure.string :as str])
(defn t [label f] (println label (try (f) (catch Throwable e (str "ERR:" (.getMessage e))))))
(t :File-2arg     #(str (java.io.File. (java.io.File. "/tmp") "x")))
(t :isAbsolute    #(.isAbsolute (java.io.File. "/tmp/x")))
(t :exists        #(.exists (io/file "/tmp")))
(t :getParentFile #(str (.getParentFile (io/file "/tmp/a/b"))))
(t :getPath       #(.getPath (io/file "/tmp/a")))
(t :resource-clj  #(let [r (io/resource "clojure/test/check/random.clj")] (when r (.getProtocol r))))
(t :toURI         #(let [r (io/resource "clojure/test/check/random.clj")] (when r (str (io/file (.toURI r))))))
(t :memoize       #(let [f (memoize (fn [x] (* x 2)))] (f 21)))
