(require '[clojure.java.io :as io] '[clojure.edn :as edn] '[clojure.test :as ct])
(defn t [label f] (println label (try (f) (catch Throwable e (str "ERR:" (.getMessage e))))))
(t :edn          #(edn/read-string "{:a 1}"))
(t :clojure-test #(some? (resolve 'clojure.test/deftest)))
(t :ct-report-multi #(str (type ct/report)))
(t :getenv       #(some? (System/getenv "HOME")))
(t :file         #(str (java.io.File. "x")))
(t :io-file      #(str (io/file "a" "b")))
(t :io-resource  #(str (io/resource "nope")))
(t :pqueue-EMPTY #(count (conj clojure.lang.PersistentQueue/EMPTY 1)))
(t :slurp-spit   #(do (spit "/tmp/cljw-probe.txt" "hi") (slurp "/tmp/cljw-probe.txt")))
