(ns qual (:refer-clojure :exclude [seq first next rest concat let when]))
(defn seq [x] :SHADOW-seq)
(defn first [x] :SHADOW-first)
(defmacro let [& _] :SHADOW-let)
(defmacro when [& _] :SHADOW-when)
(println :qseq   (clojure.core/seq [1 2]))
(println :qfirst (clojure.core/first [1 2]))
(println :qwhen  (clojure.core/when true :ok))
(println :qlet   (clojure.core/let [a 1] (clojure.core/+ a 1)))
(println :qlazy  (clojure.core/doall (clojure.core/lazy-seq (clojure.core/list 1 2))))
